services:
  frontend:
    environment:
      - VITE_BACKEND_URL=http://localhost:8080
    image: bloglist-frontend-production
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/usr/src/app
    container_name: bloglist-frontend-production
    depends_on:
      - backend

  backend:
    image: bloglist-backend-production
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/usr/src/app
    env_file:
      - ./backend/.env
    container_name: bloglist-backend-production
  
  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: bloglist-reverse-proxy
    depends_on:
      - frontend
      - backend