services:
  frontend:
    environment:
      - VITE_BACKEND_URL=http://localhost:3003
    image: bloglist-frontend
    build:
      context: ./frontend
      dockerfile: dev.Dockerfile
    volumes:
      - ./frontend:/usr/src/app
    ports:
      - 5173:5173
    container_name: bloglist-frontend-dev
    depends_on:
      - backend
  
  backend:
    image: bloglist-backend
    build:
      context: ./backend
      dockerfile: dev.Dockerfile
    volumes:
      - ./backend:/usr/src/app
    ports:
     - 3003:3003
    env_file:
      - ./backend/.env
    container_name: bloglist-backend-dev

  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: bloglist-reverse-proxy
    depends_on:
      - frontend