services:
  server:
    image: todo_backend
    build:
      context: .
      dockerfile: dev.Dockerfile
    volumes:
      - ./:/usr/src/app
    ports:
      - 3000:3000
    environment:
      - REDIS_URL=redis://redis:6378
      - MONGO_URL=mongodb://the_username:the_password@mongo:3456/the_database
    container_name: todo-back-dev
    depends_on:
      - mongo
      - redis

  mongo:
    image: mongo
    ports:
      - 3456:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: the_database

  redis:
    image: redis
    ports:
      - 6378:6379
